// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import ()

type Entry struct {
	Language       string
	Entry          string
	Status         string
	Description    string
	CommonMistakes []string
}

type SchemaVersion struct {
	Version int32
}
