// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entry
WHERE language = $1 AND entry = $2
`

type DeleteEntryParams struct {
	Language string
	Entry    string
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.Exec(ctx, deleteEntry, arg.Language, arg.Entry)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT language, entry, status, description, common_mistakes, level, data,
       updated, updated_by
FROM entry
WHERE language = $1 AND entry = $2
`

type GetEntryParams struct {
	Language string
	Entry    string
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.Language, arg.Entry)
	var i Entry
	err := row.Scan(
		&i.Language,
		&i.Entry,
		&i.Status,
		&i.Description,
		&i.CommonMistakes,
		&i.Level,
		&i.Data,
		&i.Updated,
		&i.UpdatedBy,
	)
	return i, err
}

const getLastEventID = `-- name: GetLastEventID :one
SELECT COALESCE(MAX(id), 0)::bigint AS id FROM eventlog
`

func (q *Queries) GetLastEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLastEventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO eventlog(language, entry, deleted)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertEventParams struct {
	Language string
	Entry    string
	Deleted  bool
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent, arg.Language, arg.Entry, arg.Deleted)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDictionaries = `-- name: ListDictionaries :many
SELECT language, COUNT(*) AS entries
FROM entry
GROUP BY language
`

type ListDictionariesRow struct {
	Language string
	Entries  int64
}

func (q *Queries) ListDictionaries(ctx context.Context) ([]ListDictionariesRow, error) {
	rows, err := q.db.Query(ctx, listDictionaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDictionariesRow
	for rows.Next() {
		var i ListDictionariesRow
		if err := rows.Scan(&i.Language, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT language, entry, status, description, common_mistakes, level, data,
       updated, updated_by
FROM entry
WHERE
        ($1::text IS NULL OR language = $1)
        AND ($2::text IS NULL OR entry LIKE $2)
        AND ($3::text IS NULL OR status = $3)
ORDER BY language, entry
LIMIT $5::bigint OFFSET $4::bigint
`

type ListEntriesParams struct {
	Language pgtype.Text
	Pattern  pgtype.Text
	Status   pgtype.Text
	Offset   int64
	Limit    int64
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.Language,
		arg.Pattern,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.Language,
			&i.Entry,
			&i.Status,
			&i.Description,
			&i.CommonMistakes,
			&i.Level,
			&i.Data,
			&i.Updated,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventlog = `-- name: LockEventlog :exec
LOCK TABLE eventlog IN EXCLUSIVE MODE
`

// LockEventlog takes an exclusive write lock on the eventlog table. Writers
// must call this before inserting an event so that event commits are
// serialised: a writer holds the lock until commit, so the next writer cannot
// draw its id until the previous event is visible. This keeps commit order
// equal to id order, which the log poller relies on to never skip an event.
func (q *Queries) LockEventlog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockEventlog)
	return err
}

const pruneEventlog = `-- name: PruneEventlog :execrows
DELETE FROM eventlog WHERE created < $1
`

// PruneEventlog deletes events older than the cutoff. The eventlog is only a
// delivery buffer for live consumers, not an audit trail: a restarting replica
// reloads full state and resumes from the latest id, so events past the
// consumer lag window are safe to drop.
func (q *Queries) PruneEventlog(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEventlog, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readEventlog = `-- name: ReadEventlog :many
SELECT id, language, entry, deleted, created
FROM eventlog
WHERE id > $1
ORDER BY id
LIMIT $2::bigint
`

type ReadEventlogParams struct {
	After int64
	Limit int64
}

func (q *Queries) ReadEventlog(ctx context.Context, arg ReadEventlogParams) ([]Eventlog, error) {
	rows, err := q.db.Query(ctx, readEventlog, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Eventlog
	for rows.Next() {
		var i Eventlog
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Entry,
			&i.Deleted,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEntry = `-- name: SetEntry :exec
INSERT INTO entry(
       language, entry, status, description, common_mistakes, level, data,
       updated, updated_by
) VALUES (
       $1, $2, $3, $4, $5, $6, $7,
       $8, $9
) ON CONFLICT(language, entry) DO
  UPDATE SET
       status = excluded.status,
       description = excluded.description,
       common_mistakes = excluded.common_mistakes,
       level = excluded.level,
       data = excluded.data,
       updated = excluded.updated,
       updated_by = excluded.updated_by
`

type SetEntryParams struct {
	Language       string
	Entry          string
	Status         string
	Description    string
	CommonMistakes []string
	Level          EntryLevel
	Data           *EntryData
	Updated        pgtype.Timestamptz
	UpdatedBy      string
}

func (q *Queries) SetEntry(ctx context.Context, arg SetEntryParams) error {
	_, err := q.db.Exec(ctx, setEntry,
		arg.Language,
		arg.Entry,
		arg.Status,
		arg.Description,
		arg.CommonMistakes,
		arg.Level,
		arg.Data,
		arg.Updated,
		arg.UpdatedBy,
	)
	return err
}
